version: '3'

services:
  redis:
    container_name: redis
    image: redis:latest
    networks:
    - main_net
    ports:
    - "6379:6379"
    restart: on-failure

  worker:
    build:
      context: D:\Jewelry_shop\Jewelry_Online_Shop\Jewelry_Online_Shop
    hostname: worker
    entrypoint: celery
    command: -A Jewelry_Online_Shop.celery_conf worker --loglevel=info
  db:
    image: postgres
    volumes:
    - ./data/db:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=jewelry_online_shop
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=vahid1368
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/app
    ports:
    - "8000:8000"
    environment:
    - POSTGRES_NAME=jewelry_online_shop
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=vahid1368
    depends_on:
    - db
    - redis
networks:
  main_net:

volumes:
  postgres_data:
